version: "3.5"

services:
  postgresql:
    image: "postgres:latest"
    container_name: "postgresql"
    hostname: "postgresql"
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      - transcendence
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: "backend"
    container_name: "backend"
    depends_on:
      postgresql:
        condition: service_healthy
    build: ./backend
    networks:
      - transcendence

  frontend:
    image: "frontend"
    container_name: "frontend"
    build: ./frontend
    networks:
      - transcendence
    depends_on:
      - backend

  gateway:
    image: nginx
    depends_on:
      - backend
      - frontend
    ports:
      - 3000:80
    networks:
      - transcendence
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf

networks:
  transcendence:
    driver: bridge

volumes:
  postgres_volume:
